# KidneyUS detection (1 class: kidney).
_target_: nemo_cv.components.datasets.us_rfdetr.SaUSCocoDetDataModule

data_root: ${scratch.dataset_dir}/KidneyUS
annotation_dir: ${scratch.det_annotation_dir}/KidneyUS
image_size: ${scratch.image_size}
multiplier: ${scratch.multiplier}
val_from_test: false
