#!/bin/bash
# setup-uv-env.sh — Set up this project's Python environment with uv.
#
# uv reads pyproject.toml + uv.lock at the project root and creates a
# reproducible .venv/ next to them. Use this when you want a fast,
# locked install on a local machine (no conda, no container).
#
# Usage:
#   cd <project>/src/setup
#   bash setup-uv-env.sh
#
# What it creates:
#   <project>/.venv/    — Python venv populated from uv.lock
#
# After setup:
#   source <project>/.venv/bin/activate
#   # ...or run commands without activating:
#   uv run python -c "import torch; print(torch.__version__)"

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="$(dirname "$SCRIPT_DIR")"
PROJECT_DIR="$(dirname "$SRC_DIR")"
PROJECT_NAME="$(basename "$PROJECT_DIR")"
VENV_DIR="$PROJECT_DIR/.venv"

echo "============================================"
echo " Setting up uv environment"
echo " Project: $PROJECT_NAME"
echo "============================================"
echo ""

# --- Step 1: Ensure uv is installed ---
if ! command -v uv &>/dev/null; then
    echo "[1/3] uv not found. Installing to ~/.local/bin ..."
    curl -LsSf https://astral.sh/uv/install.sh | sh

    # The installer drops uv in ~/.local/bin (or $XDG_BIN_HOME); make it
    # available for the rest of this script even if PATH wasn't reloaded.
    export PATH="${XDG_BIN_HOME:-$HOME/.local/bin}:$PATH"

    if ! command -v uv &>/dev/null; then
        echo "ERROR: uv install completed but the binary is not on PATH."
        echo "  Open a new shell and re-run this script, or add ~/.local/bin to PATH."
        exit 1
    fi
else
    echo "[1/3] uv already installed: $(uv --version)"
fi

echo ""

# --- Step 2: Sanity-check project files ---
if [[ ! -f "$PROJECT_DIR/pyproject.toml" ]]; then
    echo "ERROR: pyproject.toml not found at $PROJECT_DIR/"
    exit 1
fi
if [[ ! -f "$PROJECT_DIR/uv.lock" ]]; then
    echo "[2/3] No uv.lock found — it will be generated by 'uv sync'."
else
    echo "[2/3] Found pyproject.toml and uv.lock."
fi

echo ""

# --- Step 3: Sync the environment ---
# If the project lives on a filesystem that doesn't support cross-device
# symlinks (e.g. an NFS/NAS mount, while uv's Python cache is on the local
# disk under ~/.local/share/uv), uv's default symlink mode fails with
# "Operation not supported (os error 95)". Force copy mode in that case.
LINK_MODE_FLAG=()
if [[ "$PROJECT_DIR" == /mnt/* || "$PROJECT_DIR" == /nfs/* ]]; then
    echo "[3/3] Project is on a network/NAS mount — using --link-mode=copy."
    LINK_MODE_FLAG=(--link-mode=copy)
else
    echo "[3/3] Running 'uv sync' to create .venv/ from the lockfile..."
fi

(cd "$PROJECT_DIR" && uv sync "${LINK_MODE_FLAG[@]}")

echo ""
echo "============================================"
echo " Environment ready: $PROJECT_NAME"
echo "============================================"
echo ""
echo " Venv:  $VENV_DIR"
echo ""
echo " Activate:"
echo "   source $VENV_DIR/bin/activate"
echo ""
echo " Or run commands without activating:"
echo "   uv run python <script>.py"
echo ""
echo " Add a package:"
echo "   uv add <package>            # updates pyproject.toml + uv.lock"
echo "   uv add --dev <package>      # dev-only dependency"
echo ""
echo " Re-sync after pulling lockfile changes:"
echo "   uv sync"
echo ""
